### ISSUE TITLE
Failures in CoreMLExportTest due to undefined behavior (observed on 10.13)

### ISSUE THREAD

**Issue by nickjong** [apple/turicreate#1332]
For example:
```
___________________ CoreMLExportTest.test_linear_regression ____________________

self = <turicreate.test.test_coreml_export.CoreMLExportTest testMethod=test_linear_regression>

    def test_linear_regression(self):
        for code_string in ["b"*40, "nnnn", "v", "d", "A", "bnsCvAd"]:
            train, test = self.generate_data("regression", 100, code_string)
            model = tc.linear_regression.create(train, "target", validation_set = None)
            model.evaluate(test)  # Previous regression -- this caused errors.
>           self._test_coreml_export(model, test, True)

test_coreml_export.py:121: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_coreml_export.py:103: in _test_coreml_export
    self.assertAlmostEqual(coreml_prediction["target"], tc_prediction, delta = 1e-5)
E   AssertionError: 0.3692980279794391 != 0.5474222893547473 within 1e-05 delta
```

Due to discussion offline, this could be due to how we export dictionary features?

**Comment by znation** [comment]
@hoytak As discussed in triage today, please put up a PR ASAP to skip these tests in master (but keep this bug open and resolve it when the fixes are actually in). It's more important to keep test results in master green in the meantime. (I would do this initial PR to skip the tests, but I'm not sure which tests are affected and on which OSes they need to skip.)

**Comment by hoytak** [comment]
We should reenable these tests and reinvestigate -- it's quite possible these have been fixed.

**Comment by nickjong** [comment]
This can't be a P1, since we've had this bug for half a year, and we're no longer failing our own tests....

I did re-enable these tests, and they still fail. Which makes sense, since no fix on the CoreML side recently would affect test results on 10.13.

Ultimately, if we cannot safely export these models in a way that will work deterministically in CoreML in macOS 10.13 / iOS 11, we should document the dependency on a newer CoreML.

**Comment by nickjong** [comment]
@hoytak Not sure anyone else has the necessary context; what precisely is the dependency on CoreML? In what cases should users expect these exported Core ML models to actually work?

**Comment by znation** [comment]
If we can't get the exported models to work on 10.13, we should update their model spec version so they are limited to newer macOS releases (this will give a better user experience than just a documentation fix, as the exported model will complain in Xcode when targeting earlier macOS/iOS versions).

**Comment by hoytak** [comment]
I've been working with Guihao on this one; the issue is with columns that have dictionary features and those with categorical lists.  The way these are unpacked in old versions of CoreML means they are unpacked into uninitialized memory.  He's verified all the tests pass now; is checking today I believe on 10.13.  

@Jarvi-Izana -- is that a correct summary of the status?

**Comment by Jarvi-Izana** [comment]
@hoytak sorry for the late reply. I just finished running the pipeline with relevant `xfail` removed and it failed on mac_10_13 environment with python27.

**Comment by Jarvi-Izana** [comment]
Ok, I tried MoD with a macOS10.13 instance and it failed on python3 as well.

**Comment by Jarvi-Izana** [comment]
no code change is needed. We should keep triaging it.

**Comment by Jarvi-Izana** [comment]
We are not going to fix it due to the undefined behavior of CoreML prior to macOS version 10.14. These tests will be still marked as failure for versions prior to version 10.14.
