### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by elseagle** [apple/turicreate#191]
ImportError                               Traceback (most recent call last)
<ipython-input-5-1b519f14fefb> in <module>()
----> 1 import turicreate

/home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/__init__.py in <module>()
     28 from turicreate.version_info import __version__
     29 
---> 30 from turicreate.data_structures.sgraph import Vertex, Edge
     31 from turicreate.data_structures.sgraph import SGraph
     32 from turicreate.data_structures.sarray import SArray

/home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/data_structures/__init__.py in <module>()
     15 __all__ = ['sframe', 'sarray', 'sgraph', 'sketch', 'image']
     16 
---> 17 from . import image
     18 from . import sframe
     19 from . import sarray

ImportError: cannot import name image

**Comment by elseagle** [comment]
`ImportError                               Traceback (most recent call last)
<ipython-input-5-1b519f14fefb> in <module>()
----> 1 import turicreate

/home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/__init__.py in <module>()
     28 from turicreate.version_info import __version__
     29 
---> 30 from turicreate.data_structures.sgraph import Vertex, Edge
     31 from turicreate.data_structures.sgraph import SGraph
     32 from turicreate.data_structures.sarray import SArray

/home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/data_structures/__init__.py in <module>()
     15 __all__ = ['sframe', 'sarray', 'sgraph', 'sketch', 'image']
     16 
---> 17 from . import image
     18 from . import sframe
     19 from . import sarray

ImportError: cannot import name image`

**Comment by gustavla** [comment]
Hi @elseagle, thanks for trying out Turi Create! Let's see if we can figure out what's going on. If you do:
```
ls /home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/data_structures/
```
Does it list the file `image.py`? It should, among other files. If this is the case, you can try to uninstall and re-install `pip uninstall -y turicreate && pip install turicreate` to see if that fixes it.

**Comment by elseagle** [comment]
it lists `image.py`

**Comment by elseagle** [comment]
`ls /home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/data_structures/
gframe.py   grouped_sframe.py   image.py   __init__.py   sarray_builder.py   sarray.py   sframe_builder.py   sframe.py   sgraph.py   sketch.py
gframe.pyc  grouped_sframe.pyc  image.pyc  __init__.pyc  sarray_builder.pyc  sarray.pyc  sframe_builder.pyc  sframe.pyc  sgraph.pyc  sketch.pyc`

**Comment by elseagle** [comment]
I have `pip uninstall -y turicreate && pip install turicreate` still giving the same error

**Comment by gustavla** [comment]
How are you running `import turicreate`? It looks like it's through IPython. Does this also happen if you do it in the regular interactive python prompt from an empty directory?

**Comment by elseagle** [comment]
yes i am runnig through IPython. and I just ran it in shell and I'm getting 
`Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import turicreate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/__init__.py", line 30, in <module>
    from turicreate.data_structures.sgraph import Vertex, Edge
  File "/home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/data_structures/__init__.py", line 18, in <module>
    from . import sframe
  File "/home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/data_structures/sframe.py", line 16, in <module>
    from ..connect import main as glconnect
  File "/home/elseagle/venv/local/lib/python2.7/site-packages/turicreate/connect/main.py", line 13, in <module>
    from ..cython.cy_unity import UnityGlobalProxy
ImportError: libblas.so.3: cannot open shared object file: No such file or directory
>>>`

**Comment by gustavla** [comment]
It looks like you are missing a dependency. Make sure to read through https://github.com/apple/turicreate#installation, it will describe how to install all the dependencies. Since you are on Linux, you will want to follow the instructions here: https://github.com/apple/turicreate/blob/master/LINUX_INSTALL.md .

Let me know how it turns out!

**Comment by elseagle** [comment]
okay

**Comment by elseagle** [comment]
I have fixed it.. I didn't have the libblas dependency. I think this should be left open for other wsl users to see. Thanks a bunch @gustavla

**Comment by gustavla** [comment]
Great! Since the dependency is documented in the installation instructions and closed issues are still viewable and searchable, I hope you don't mind if I go ahead an close it.

**Comment by fuomag9** [comment]
For those who are using manjaro/arch, in my case I fixed the issue with `sudo pacman -S gconf`

**Comment by raj9650sahni** [comment]
> Hi @elseagle 
hey i am getting os error . i am using turicreate in window having ubuntu=18.04 Lts . when i try to import SFrame i got this error help me

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in __init__(self, data, format, _proxy)
    834                     url = _make_internal_url(data)
--> 835                     self.__proxy__.load_from_sframe_index(url)
    836                 elif _format == "empty":

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_sframe_index()

cy_sframe.pyx in turicreate._cython.cy_sframe.UnitySFrameProxy.load_from_sframe_index()

OSError: /home/raj/E:/work/ml_assignment4/song_data.sframe not found. ErrMsg: file not exist in /home/raj/E:/work/ml_assignment4/song_data.sframe

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-2-ea10cb95d86f> in <module>
----> 1 sf = turicreate.SFrame("E:\work\ml_assignment4\song_data.sframe")

~/venv/lib/python3.6/site-packages/turicreate/data_structures/sframe.py in __init__(self, data, format, _proxy)
    837                     pass
    838                 else:
--> 839                     raise ValueError("Unknown input type: " + format)
    840 
    841     @staticmethod

~/venv/lib/python3.6/site-packages/turicreate/_cython/context.py in __exit__(self, exc_type, exc_value, traceback)
     48             if not self.show_cython_trace:
     49                 # To hide cython trace, we re-raise from here
---> 50                 raise exc_type(exc_value)
     51             else:
     52                 # To show the full trace, we do nothing and let exception propagate

OSError: /home/raj/E:/work/ml_assignment4/song_data.sframe not found. ErrMsg: file not exist in /home/raj/E:/work/ml_assignment4/song_data.sframe

**Comment by dyaneshwer** [comment]
Hi @gustavla help me with this issue please.thanks in advance😊

**Comment by dyaneshwer** [comment]
@raj9650sahni did u resolve the issue if so how?
