### ISSUE TITLE
Style transfer: Bad results. Greenish, reddish, wavy artifacts.

### ISSUE THREAD

**Issue by banoslo** [apple/turicreate#2031]
I am trying to apply style transfer on images. Unfortunately most results have greenish, reddish, wavy artifacts.

This is my setting:
I use Ubuntu 18 and the Turicreate 5.5 version for Python 3.6 with mxnet CUDA 9.1 on a NVIDIA GTX 950. I use the code lines from the Docs with a 100.000 (on one example 10000) training iterations.

Maybe it is related to https://github.com/apple/turicreate/issues/666 and https://github.com/apple/turicreate/issues/1341

4 examples with models can be downloaded here: https://drive.google.com/open?id=1tTkcpryOW4u5B4MBy4fGHxiBtU2bZU-j

Here is one example:

Output:
![output1](https://user-images.githubusercontent.com/2702147/59059501-69ef9f80-889f-11e9-8394-4a692732157f.png)

Input:
![input1](https://user-images.githubusercontent.com/2702147/59059525-783dbb80-889f-11e9-91bb-5ce93ca87f28.png)

Style:
![style](https://user-images.githubusercontent.com/2702147/59059540-7ffd6000-889f-11e9-9256-aa3b0b7d4225.png)

Here is another example:

Output:
![output1](https://user-images.githubusercontent.com/2702147/59059640-c6eb5580-889f-11e9-890b-74bba4dc0ed5.png)

Input:
![input1](https://user-images.githubusercontent.com/2702147/59059650-ceaafa00-889f-11e9-905b-aec19efe98c2.png)

Style:
![style](https://user-images.githubusercontent.com/2702147/59059674-d66a9e80-889f-11e9-94c1-a815149dffec.png)

As a side note: The original paper seems to have same issues (https://arxiv.org/pdf/1610.07629.pdf). Take a look at page 16 (Roy Lichtenstein, Bicentennial Print (1975)). Zoom-in to the Brad Pitt portrait.

Best regards,

**Comment by romanoss** [comment]
I had the same results. More Iterations, more content images don't help.
I have quickly looked into the original paper and you are probably right. It seems to be a feature of the model and this is underwhelming to say the least. Especially if one compares the results to the ones from a vgg19 model.

**Comment by TobyRoseman** [comment]
@romanoss - Yes, please share your images for comparison. Having more examples of this problem would be helpful. Thank you.

**Comment by romanoss** [comment]
@TobyRoseman
orig vs vgg19 vs tc 5.4
![stata](https://user-images.githubusercontent.com/2591631/59882751-6128be80-93b3-11e9-8749-a2c046459be3.png)
![IMG_6058](https://user-images.githubusercontent.com/2591631/59882775-70a80780-93b3-11e9-8c4e-7d246dc6ddee.png)
![IMG_6057](https://user-images.githubusercontent.com/2591631/59882816-86b5c800-93b3-11e9-94f8-46c7e62bd7b2.png)
![1_4139](https://user-images.githubusercontent.com/2591631/59882838-8f0e0300-93b3-11e9-9586-79a96389aab0.png)
![1_4139 (1)](https://user-images.githubusercontent.com/2591631/59882851-96cda780-93b3-11e9-84e8-25771256e8ea.png)

**Comment by romanoss** [comment]
@TobyRoseman
this should be resolved now - as I tried it with the 5.5 changes

**Comment by banoslo** [comment]
Wait. Why did you close the ticket. This is not solved for version 5.5 actually. Did you reproduce the artifacts with my image files? You can easily reproduce them with files at https://drive.google.com/open?id=1tTkcpryOW4u5B4MBy4fGHxiBtU2bZU-j as I written before.

**Comment by TobyRoseman** [comment]
@banoslo - apologizes for closing the issues. We improved style transfer with the 5.5 release and @romanoss seemed to indicate this issue had been fixed. Can you please summarize what is still outstanding with this issue?

**Comment by romanoss** [comment]
hmm- I am not sure about your problem @banoslo .
Generally, it seems that this model is prone to produce some stripes, as one can see in the original paper too. The worst artifacts went away for me with the 5.5 patch

Nevertheless, there are some points I don't understand right now.
Actual changes and some testing in the past indicate that one should calculate the model with iterations = styles * 10000 (which is ridiculous on a Cpu :) )
I did not try this, but it seems that the model converges fast (~3000 iters) and stays that way for a long time and then improves again at a high iteration value.

Did you try high iteration values?

regards
Roman

**Comment by banoslo** [comment]
@romanoss @TobyRoseman 

As written in my description, I use 5.5 with 10000 - 100000 iterations and have the issues as shown in my examples (also download the files from Google Drive).

Best

**Comment by romanoss** [comment]
@TobyRoseman @banoslo 
Ok - I managed to test the 5.6 version of style transfer in tc
I trained 1 style for about 10000 iterations in (512,512) and as far as one can see the problems of version 5.4 are resolved here(stripes version is 5.4)

![IMG_6204](https://user-images.githubusercontent.com/2591631/61284317-feaebc80-a7be-11e9-8ac5-d0af4999dfe0.jpg)
![IMG_6205](https://user-images.githubusercontent.com/2591631/61284333-0706f780-a7bf-11e9-9de7-3993b1ef7b40.jpg)

btw default iterations changed from 5*numStyles+2000 to numStyles*10000 which is quite a difference
fun fact: if you train 20 styles this is 200000 iterations which are 5 days on a Tesla T4 and probably over a year for a mac :)

**Comment by banoslo** [comment]
Thanks for your reply.

But if you zoom in, you will see a dramatic increase in many slight greenish violett waves in the first image!

**Comment by romanoss** [comment]
@banoslo 
first image is tc 5.4 version, that really had severe problems - there was an update in 5.5, which is much nicer

**Comment by banoslo** [comment]
Thanks for you fast reply.

Agree, the first one is problematic.

But the second image still has got the greenish red wave issue. Take a look at the right side of the nose. Some light red/green issues at the beard. The beanie has the typical green all over the place and a profound red/green issue at the upper right.

Best regards

**Comment by romanoss** [comment]
@banoslo 
I can see what you mean.
hmm-I guessed the red/green values at the beanie were a style feature and I did not recognize the small wave at the right side of the nose -hmm - hard to say. @TobyRoseman  what do u think?

**Comment by romanoss** [comment]
@banoslo I can try this one again with 10000 it with the coco image set instead of my 200 private content images

**Comment by romanoss** [comment]
@banoslo  you are definitely right - the issue still exists - to a lesser degree but it exists.
Here are two more pictures:
5.4
![IMG_6209](https://user-images.githubusercontent.com/2591631/61297862-6aa01d80-a7dd-11e9-8353-2675c5c51232.JPG)

5.6
![IMG_6207](https://user-images.githubusercontent.com/2591631/61297873-74298580-a7dd-11e9-9134-683c8690c100.jpg)

@TobyRoseman can you see it?

**Comment by banoslo** [comment]
Thanks Roman for verifying this. Best regards!

**Comment by romanoss** [comment]
@abhishekpratapa can you pls take a look?

**Comment by TobyRoseman** [comment]
@romanoss and @banoslo - Thanks for the detailed discussion. I do see what you mean now; looks like 5.6 is a big improvement but we still have a way to go. Do either of you have any ideas about how this could be fixed?

@abhishekpratapa - what do you think?

**Comment by romanoss** [comment]
@abhishekpratapa added some padding layers - maybe they can be tuned?

**Comment by banoslo** [comment]
Maybe you could ask Leon Gatys, he works at Apple now as well.

**Comment by romanoss** [comment]
@TobyRoseman @banoslo @abhishekpratapa

I checked the original paper and found:

We used the same network architecture as in Johnson et al. (2016), 
except for two key details:
zero-padding is replaced with mirror-padding, and transposed convolutions (also sometimes called
deconvolutions) are replaced with nearest-neighbor upsampling followed by a convolution. The
use of mirror-padding avoids border patterns sometimes caused by zero-padding in SAME-padded
convolutions, **while the replacement for transposed convolutions avoids checkerboard patterning**, as
discussed in Odena et al. (2016). 

This model seems to be built like the  tensorflow/magenta equivalent
Adding the padding was done in 5.5
Avoiding the checkerboard patterning seems to be the way to go. 
Can you put it on 5.8?

**Comment by TobyRoseman** [comment]
Is this still an issue with the latest version of TuriCreate? Since 5.8 we have done a large rewrite of the Style Transfer Toolkit.

**Comment by TobyRoseman** [comment]
I have not heard back here. I'm going to close this issue. Please reopen, if it is still a problem in the latest version of TuriCreate.
