### ISSUE TITLE
Cant create coreml model - Fatal python error

### ISSUE THREAD

**Issue by siideffect** [apple/turicreate#213]
Hello, this issue is similare to #112
I am trying to creating a custom core mlmodel , but seems there is a problem related to python, which is making me going crazy.

This is the output terminal : 

```
***:MLClassfier ***$ python script.py 
Unsupported image format. Supported formats are JPEG and PNG	 file: /Users/***/Downloads/MLClassfier/dataset/rice/.DS_Store
Unsupported image format. Supported formats are JPEG and PNG	 file: /Users/***/Downloads/MLClassfier/dataset/.DS_Store
Materializing SFrame...
Done.
[00:09:26] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[00:09:26] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
Resizing images...
2018-01-24 00:09:28.880 Turi Create Visualization[632:9920] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 3. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2018-01-24 00:09:28.880 Turi Create Visualization[632:9920] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 3. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
2018-01-24 00:09:28.880 Turi Create Visualization[632:9920] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 3. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
Performing feature extraction on resized images...
Completed 269/269
PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.

WARNING: The number of feature dimensions in this problem is very large in comparison with the number of examples. Unless an appropriate regularization value is set, this model may not provide accurate predictions for a validation/test set.
WARNING: Detected extremely low variance for feature(s) '__image_features__' because all entries are nearly the same.
Proceeding with model training using all features. If the model does not provide results of adequate quality, exclude the above mentioned feature(s) from the input dataset.
Logistic regression:
--------------------------------------------------------
Number of examples          : 258
Number of classes           : 2
Number of feature columns   : 1
Number of unpacked features : 2048
Number of coefficients    : 2049
Starting L-BFGS
--------------------------------------------------------
+-----------+----------+-----------+--------------+-------------------+---------------------+
| Iteration | Passes   | Step size | Elapsed Time | Training-accuracy | Validation-accuracy |
+-----------+----------+-----------+--------------+-------------------+---------------------+
| 1         | 4        | 0.001938  | 1.072405     | 0.879845          | 0.909091            |
| 2         | 7        | 0.500000  | 1.143742     | 0.980620          | 1.000000            |
| 3         | 8        | 0.500000  | 1.178049     | 0.980620          | 1.000000            |
| 4         | 9        | 0.500000  | 1.225127     | 0.980620          | 1.000000            |
| 5         | 10       | 0.500000  | 1.265521     | 0.984496          | 1.000000            |
| 6         | 11       | 0.500000  | 1.311589     | 0.992248          | 1.000000            |
+-----------+----------+-----------+--------------+-------------------+---------------------+
TERMINATED: Iteration limit reached.
This model may not be optimal. To improve it, consider increasing `max_iterations`.
1.0
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

```

Note that, i have installed python 2.7.14 from python.org 
Then i went for pip install -U turicreate
Im not a terminal / python wizard, but i have read the issue #112 with attention. 
Why is python crashing? I ve tried plenty of times

**Comment by srikris** [comment]
Thanks for trying it out and sorry for the trouble. coremltools currently doesn't support Python.org python. Its a known issue and we are seeing what we can do about it. In the meantime, I'd recommend you use anaconda or system python. 

In order to fully remove python.org python, I've use these instructions before and they seemed to work for me:
https://stackoverflow.com/questions/13538586/uninstall-python-org-version-of-python2-7-in-favor-of-default-os-x-python2-7

**Comment by siideffect** [comment]
@srikris Thanks for your response , i have been able to remove python package i have previously installed. I ve also had to install pip again in order to install turicreate.

The command i ve inserted to install turicreate is 
`
pip install turicreate
`


which unfortunately fails, giving me this error 


```
Installing collected packages: numpy, pandas, six, protobuf, coremltools, decorator, prettytable, graphviz, mxnet, turicreate
  Found existing installation: numpy 1.8.0rc1
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0rc1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/r0/wqmhc5vn5v1fdw0tgzkvv1t40000gn/T/pip-Y4oyWZ-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'
```

**Comment by srikris** [comment]
Our instructions in the README.md suggest to use virtualenv. I strongly recommend that over doing sudo (which you would need to do to install without a virtualenv)

**Comment by siideffect** [comment]
I have been able to install turicreate using a virtual environment as you suggested, thank you very much @srikris

**Comment by znation** [comment]
Sounds like this is resolved - thanks for the info @siideffect!

**Comment by AbhinandanBedi** [comment]
I am still getting the crash error even after re-installing python 2.7. Can anyone please clearly elaborate how to fix the issue?

**Comment by siideffect** [comment]
Use the default version of python installed on your Mac, and follow the instructions in README file of the repo to setup a virtual environment correctly. Once you setup it, you will be able to install turicreate in the virtual environment you just created.

**Comment by srikris** [comment]
@AbhinandanBedi Can you elaborate on which version of python you have? (run `which python`). Can you share what your crash is? That would help too.

**Comment by AbhinandanBedi** [comment]
@srikris 
![screen shot 2018-02-02 at 1 46 32 am](https://user-images.githubusercontent.com/20858369/35701126-12cc92e6-07bb-11e8-8120-a05d30c00fe7.png)
![screen shot 2018-02-02 at 12 24 46 am](https://user-images.githubusercontent.com/20858369/35701140-1a1f14e2-07bb-11e8-8f8a-53a5a093d707.png)

Any help?

**Comment by znation** [comment]
@AbhinandanBedi with Python in `/Library/Frameworks/Python.framework/Versions/2.7`, using virtualenv from `/Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenv`, I'm unable to reproduce this issue with turicreate==4.0.

Can you provide some more info? Exactly which commands are you running, in which order? What version(s) of Python do you have on your machine, and how did you install them?

**Comment by AbhinandanBedi** [comment]
@znation I have successfully installed the turicreate using the command `pip install turicreate` Now, I am running this "classifier.py" file with the command `python classifier.py`After running, it opens the python launcher, Turi Create Visualization but in the end it shows that Fatal Error as mentioned in above screenshots. 

![screen shot 2018-02-02 at 2 08 26 am](https://user-images.githubusercontent.com/20858369/35702169-63447524-07be-11e8-8521-9d9e83fc14f4.png)

**Comment by znation** [comment]
Thanks @AbhinandanBedi. Looks like we may still have a bug here; I'll reopen this issue so we can track it. We'll try to reproduce it with the code you have provided.

**Comment by AbhinandanBedi** [comment]
Worked successfully for me after running virtual environment in Anaconda.
@znation @siideffect @srikris

**Comment by srikris** [comment]
Yes. The previous python you were using was from Downloaded from python.org. This will be fixed on coremltools-0.8

**Comment by srikris** [comment]
@AbhinandanBedi Coremltools 0.8 should have fixed this issue. Can you run your script again after upgrading using:

```
pip install coremltools --upgrade
```
